# Generated by Django 4.1.4 on 2023-03-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('senddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
