# Generated by Django 4.1.4 on 2022-12-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='staff',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
