# Generated by Django 4.1.7 on 2023-05-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinvitation',
            name='validate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(choices=[('S', 'sécretaire'), ('D', 'directeur'), ('RCLI', 'responsable de concours licence informatique'), ('RCMI', 'responsable de concours master 1 informatique'), ('RCINGI', 'responsable de concours ingenieur informatique')], default='S', max_length=50),
        ),
    ]
