# Generated by Django 4.1.4 on 2023-01-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staffinvitation_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(default='default.jpeg', upload_to=''),
        ),
    ]
