# Generated by Django 4.1.4 on 2023-01-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_staff_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='avatar',
            field=models.ImageField(default='default.jpeg', upload_to=''),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='bio',
            field=models.TextField(default='do you know ngdream likes banana ???'),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='role',
            field=models.CharField(choices=[('S', 'sécretaire'), ('D', 'directeur'), ('RCL1I', 'responsable de concours licence informatique'), ('RCM1I', 'responsable de concours master 1 informatique'), ('RCINGI', 'responsable de concours ingenieur informatique')], default='S', max_length=50),
        ),
        migrations.DeleteModel(
            name='staff',
        ),
    ]
