# Generated by Django 4.1.4 on 2023-01-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_emailuser_avatar_emailuser_bio_emailuser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='contact',
            field=models.CharField(default='+237 698 55 55 11', max_length=50, verbose_name=''),
        ),
    ]
