# Generated by Django 4.1.4 on 2023-03-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_emailuser_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='contact',
            field=models.CharField(default='+237 698 55 55 11', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffinvitation',
            name='role',
            field=models.CharField(choices=[('S', 'sécretaire'), ('D', 'directeur'), ('RCL1I', 'responsable de concours licence informatique'), ('RCM1I', 'responsable de concours master 1 informatique'), ('RCINGI', 'responsable de concours ingenieur informatique')], default='S', max_length=100),
        ),
    ]
