# Generated by Django 4.1.4 on 2023-03-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_annonce', models.DateField(auto_now_add=True)),
                ('date_inscription', models.DateField(null=True, verbose_name="date limite d'inscription")),
                ('date_debut', models.DateField(null=True, verbose_name="date de d'ébut")),
                ('nbr_place', models.IntegerField(default=50, verbose_name='nombre maximum de place')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentType',
            fields=[
                ('nom', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('color', models.CharField(default='#00f', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='WritingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tournaments.tournament', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentSubject',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('tournaments', models.ManyToManyField(to='Tournaments.tournamenttype')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tournaments.tournamenttype'),
        ),
        migrations.CreateModel(
            name='OralSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tournaments.tournament', verbose_name='')),
            ],
        ),
    ]
