# Generated by Django 4.1.4 on 2023-03-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentsubject',
            name='tournaments',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tournaments.tournamenttype'),
        ),
    ]
