# Generated by Django 4.1.4 on 2022-12-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='date_lancement',
        ),
        migrations.AddField(
            model_name='tournament',
            name='suit',
            field=models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')], default=0),
        ),
        migrations.AlterField(
            model_name='oralsession',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='writingsession',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
