# Generated by Django 4.1.4 on 2023-03-18 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0002_remove_tournamentsubject_tournaments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsubject',
            name='tournaments',
            field=models.ManyToManyField(to='Tournaments.tournamenttype'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tournaments.tournamenttype'),
        ),
    ]
