# Generated by Django 4.1.4 on 2022-12-15 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0002_remove_tournament_date_lancement_tournament_suit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='suit',
        ),
        migrations.AddField(
            model_name='tournament',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='writingsession',
            name='tournament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tournaments.tournament', verbose_name=''),
        ),
    ]
