# Generated by Django 4.1.4 on 2022-12-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0003_remove_tournament_suit_tournament_year_in_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='S0', max_length=2),
        ),
    ]
