# Generated by Django 4.1.4 on 2023-03-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0003_tournamentsubject_tournaments_alter_tournament_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentsubject',
            name='tournaments',
        ),
    ]
