# Generated by Django 4.1.4 on 2022-12-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0004_remove_tournament_year_in_school_tournament_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('', 'Concours licence I informatique'), ('SO', 'Concours licence I informatique'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='S0', max_length=2),
        ),
    ]
