# Generated by Django 4.1.4 on 2023-03-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0005_tournamentsubject_tournaments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writingsession',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='OralSession',
        ),
        migrations.DeleteModel(
            name='WritingSession',
        ),
    ]
