# Generated by Django 4.1.4 on 2022-12-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0006_alter_tournament_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('cl1i', 'Concours licence I informatique'), ('cl1m', 'Concours licence I Management'), ('cing1i', 'Concours ingenieur I informatique'), ('cing3i', 'Coucours ingenieur III informatique'), ('cm1m', 'Concours Master I Management'), ('cm1i', 'Concours Master I informatique ')], default='S0', max_length=7),
        ),
    ]
