# Generated by Django 4.1.4 on 2022-12-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0007_alter_tournament_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='titre',
        ),
        migrations.AddField(
            model_name='tournament',
            name='nbr_place',
            field=models.IntegerField(default=300),
        ),
    ]
