# Generated by Django 4.1.4 on 2023-01-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0008_remove_tournament_titre_tournament_nbr_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date_inscription',
            field=models.DateTimeField(null=True),
        ),
    ]
