# Generated by Django 4.1.4 on 2023-01-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0009_tournament_date_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_inscription',
            field=models.DateTimeField(null=True, verbose_name="date limite d'inscription"),
        ),
    ]
