# Generated by Django 4.1.4 on 2023-01-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0010_alter_tournament_date_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='nbr_place',
            field=models.IntegerField(default=50),
        ),
    ]
