# Generated by Django 4.1.4 on 2023-01-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0011_alter_tournament_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_annonce',
            field=models.DateField(auto_now_add=True),
        ),
    ]
