# Generated by Django 4.1.4 on 2023-01-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0012_alter_tournament_date_annonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_inscription',
            field=models.DateField(null=True, verbose_name="date limite d'inscription"),
        ),
    ]
