# Generated by Django 4.1.4 on 2023-01-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0013_alter_tournament_date_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date_debut',
            field=models.DateField(null=True),
        ),
    ]
