# Generated by Django 4.1.4 on 2023-03-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0014_tournament_date_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_debut',
            field=models.DateField(null=True, verbose_name="date de d'ébut"),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='nbr_place',
            field=models.IntegerField(default=50, verbose_name='nombre maximum de place'),
        ),
    ]
