# Generated by Django 4.1.4 on 2022-12-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('sex', models.CharField(max_length=1, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('cni_number', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=100, null=True)),
                ('valeur', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymat_number', models.IntegerField(null=True)),
                ('tournaments', models.ManyToManyField(to='Tournaments.tournament')),
            ],
        ),
    ]
