# Generated by Django 4.1.4 on 2023-03-12 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tournaments', '0015_alter_tournament_date_debut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymat_number', models.CharField(max_length=6, null=True)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='nom')),
                ('lastname', models.CharField(max_length=100, null=True, verbose_name='prenom')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('sex', models.CharField(choices=[('M', 'masculin'), ('F', 'feminin')], default='M', max_length=1, verbose_name='votre sex')),
                ('birth_date', models.DateField(null=True, verbose_name='date de naissance')),
                ('birth_place', models.CharField(max_length=100, null=True, verbose_name='lieu de naissance')),
                ('bacc', models.BooleanField(default=True, verbose_name='avez vous le baccaléaurat??')),
                ('obtentionyear', models.IntegerField(default=2022, null=True, verbose_name="année d'obtention")),
                ('exschool', models.CharField(max_length=100, null=True, verbose_name='votre établissement')),
                ('hasrepeated', models.BooleanField(default=False, verbose_name='avez vous déja redoublé ?')),
                ('repeatedclasse', models.CharField(blank=True, choices=[('autre', 'autre'), ('sizieme', 'sizieme'), ('cinquieme', 'cinquieme'), ('quatrieme', 'quatrieme'), ('troizieme', 'troizieme'), ('seconde', 'seconde'), ('pemiere', 'premiere'), ('terminale', 'terminale')], max_length=50, null='terminale', verbose_name='classe repété')),
                ('mention', models.CharField(default='passable', max_length=100)),
                ('examcenter', models.CharField(default='yaoundé', max_length=100, verbose_name="centre d'examination")),
                ('exschoolcity', models.CharField(max_length=100, null=True, verbose_name='ville de votre établissement')),
                ('series', models.CharField(default='E', max_length=10, verbose_name='votre série')),
                ('nationality', models.CharField(max_length=100, null=True, verbose_name='nationnalité')),
                ('email', models.EmailField(max_length=100, null=True)),
                ('baccmark', models.IntegerField(default=10, verbose_name='moyenne générale au bacc')),
                ('probatoiremark', models.IntegerField(default=10, verbose_name='moyenne générale au probatoire')),
                ('phone', models.CharField(max_length=100, null=True, verbose_name='téléphone')),
                ('region', models.CharField(max_length=100, null=True)),
                ('adresse', models.CharField(max_length=100, null=True)),
                ('cni_number', models.PositiveBigIntegerField(null=True, verbose_name='numéro de cni')),
                ('nompere', models.CharField(max_length=100, null=True, verbose_name='nom de la mere')),
                ('nommere', models.CharField(max_length=100, null=True, verbose_name='nom du pere')),
                ('professionmere', models.CharField(max_length=100, null=True, verbose_name='profession de la mere')),
                ('professionpere', models.CharField(max_length=100, null=True, verbose_name='profession du père')),
                ('situation', models.CharField(default='mariées', max_length=100)),
                ('nombreenfant', models.IntegerField(default=1, verbose_name="nombre d'enfant")),
                ('nombreenfantes', models.IntegerField(default=0, verbose_name="nombre d'enfant en etudes superieur")),
                ('adresseparent', models.CharField(max_length=100, null=True, verbose_name='adresse des parents')),
                ('photo_recto_cni', models.ImageField(blank=True, null=True, upload_to='cni')),
                ('photo_verso_cni', models.ImageField(blank=True, null=True, upload_to='cni')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Noteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField(default=15)),
                ('appreciation', models.TextField(default='a de la motivation')),
                ('candidat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidacy')),
            ],
        ),
        migrations.CreateModel(
            name='Notee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=100, null=True)),
                ('valeur', models.IntegerField(default=10)),
                ('candidat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidacy')),
            ],
        ),
    ]
