# Generated by Django 4.1.4 on 2022-12-16 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0007_alter_tournament_type'),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Note',
            new_name='Notee',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='tournaments',
        ),
        migrations.AddField(
            model_name='candidacy',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='photo_recto_cni',
            field=models.ImageField(null=True, upload_to='cni'),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='photo_verso_cni',
            field=models.ImageField(null=True, upload_to='cni'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='cni_number',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
