# Generated by Django 4.1.4 on 2023-03-18 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0006_remove_writingsession_tournament_delete_oralsession_and_more'),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OralNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('note', models.IntegerField(default=10)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidacy')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tournaments.tournament', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='WritingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('note', models.IntegerField(default=10)),
                ('observation', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidacy')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tournaments.tournament', verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='noteo',
            name='candidat',
        ),
        migrations.DeleteModel(
            name='Notee',
        ),
        migrations.DeleteModel(
            name='Noteo',
        ),
    ]
