# Generated by Django 4.1.4 on 2023-01-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_candidacy_adresse_candidacy_adresseparent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidacy',
            name='photo_recto_cni',
            field=models.ImageField(blank=True, null=True, upload_to='cni'),
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='photo_verso_cni',
            field=models.ImageField(blank=True, null=True, upload_to='cni'),
        ),
    ]
