# Generated by Django 4.1.4 on 2023-03-19 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0006_remove_writingsession_tournament_delete_oralsession_and_more'),
        ('candidate', '0003_remove_oralnote_date_remove_oralnote_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidacy',
            name='anonymat_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='series',
            field=models.CharField(default='c', max_length=10, verbose_name='votre série'),
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tournaments.tournament'),
        ),
    ]
