# Generated by Django 4.1.4 on 2023-01-15 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0009_tournament_date_inscription'),
        ('candidate', '0004_alter_candidacy_photo_recto_cni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidacy',
            name='candidate',
        ),
        migrations.AddField(
            model_name='candidacy',
            name='anonymat_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='adresseparent',
            field=models.CharField(max_length=100, null=True, verbose_name='adresse des parents'),
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='repeatedclasse',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='classe repété'),
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='sex',
            field=models.CharField(max_length=1, null=True, verbose_name='votre sex'),
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
