# Generated by Django 4.1.4 on 2023-03-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_alter_candidacy_anonymat_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidacy',
            name='repeatedclasse',
            field=models.CharField(blank=True, max_length=50, null='terminale', verbose_name='classe repété'),
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='sex',
            field=models.CharField(default='M', max_length=1, verbose_name='votre sex'),
        ),
    ]
