# Generated by Django 4.1.4 on 2023-01-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_remove_candidacy_candidate_candidacy_anonymat_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidacy',
            old_name='birth_place',
            new_name='lieu de naissance',
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='bacc',
            field=models.BooleanField(default=True, verbose_name='avez vous le baccaléaurat??'),
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='date de naissance'),
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='cni_number',
            field=models.PositiveBigIntegerField(null=True, verbose_name='numéro de cni'),
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='lastname',
            field=models.CharField(max_length=100, null=True, verbose_name='prenom'),
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='nationality',
            field=models.CharField(max_length=100, null=True, verbose_name='nationnalité'),
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='repeatedclasse',
            field=models.CharField(blank=True, choices=[('autre', 'autre'), ('sizieme', 'sizieme'), ('cinquieme', 'cinquieme'), ('quatrieme', 'quatrieme'), ('troizieme', 'troizieme'), ('seconde', 'seconde'), ('pemiere', 'premiere'), ('terminale', 'terminale')], max_length=50, null='terminale', verbose_name='classe repété'),
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='sex',
            field=models.CharField(choices=[('M', 'masculin'), ('F', 'masculin')], default='M', max_length=1, verbose_name='votre sex'),
        ),
    ]
