# Generated by Django 4.1.4 on 2023-01-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_remove_candidacy_lieu de naissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidacy',
            name='sex',
            field=models.CharField(choices=[('M', 'masculin'), ('F', 'feminin')], default='M', max_length=1, verbose_name='votre sex'),
        ),
    ]
