# Generated by Django 4.1.4 on 2023-01-18 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_alter_candidacy_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='notee',
            name='candidat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidacy'),
        ),
        migrations.AddField(
            model_name='noteo',
            name='appreciation',
            field=models.TextField(default='a de la motivation'),
        ),
        migrations.AddField(
            model_name='noteo',
            name='candidat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidacy'),
        ),
        migrations.AddField(
            model_name='noteo',
            name='valeur',
            field=models.IntegerField(default=15),
        ),
    ]
