# Generated by Django 4.1.4 on 2023-01-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_notee_candidat_noteo_appreciation_noteo_candidat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notee',
            name='valeur',
            field=models.IntegerField(default=10),
        ),
    ]
