# Generated by Django 4.1.4 on 2023-01-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_alter_notee_valeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notee',
            name='valeur',
            field=models.CharField(default=10, max_length=20),
        ),
    ]
