# Generated by Django 4.1.4 on 2023-01-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_alter_notee_valeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notee',
            name='valeur',
            field=models.IntegerField(default=10),
        ),
    ]
