# Generated by Django 4.1.4 on 2023-01-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_alter_notee_valeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidacy',
            name='anonymat_number',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
